#!/usr/bin/env bash

if
  [[ -s "/home/action/.rvm/gems/ruby-2.1.2@rails4.1/environment" ]]
then
  source "/home/action/.rvm/gems/ruby-2.1.2@rails4.1/environment"
  exec rails "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/action/.rvm/gems/ruby-2.1.2@rails4.1/environment'" >&2
  exit 1
fi
